extends Node


@export var resource_type : Dictionary = {
	"Ore":GLOBALVARIABLES.RESOURCE_TYPE.ORE,
	"Wood":GLOBALVARIABLES.RESOURCE_TYPE.WOOD,
	"Oil":GLOBALVARIABLES.RESOURCE_TYPE.OIL,
	"Metal":GLOBALVARIABLES.RESOURCE_TYPE.METAL,
	"Plank":GLOBALVARIABLES.RESOURCE_TYPE.PLANK,
	"Refined Oil":GLOBALVARIABLES.RESOURCE_TYPE.REFINED_OIL,
	}

